### ISSUE TITLE
Persistent identifiers

### ISSUE THREAD

**Issue by perglr** [DataStewardshipWizard/dsw-common#1]
- [x] Converting old KM to the new event-based one with UUIDs.
- [x] Cross-linking questions (cross references)

## Stories:
- [x] #16 
- [x] #69

**Comment by MarekSuchanek** [comment]
What exactly is meant by "URLs"?

**Comment by MarekSuchanek** [comment]
@perglr 

Is by URL meant something like: `/question/{uuid}`? For what types do we need it?

**Comment by perglr** [comment]
Needed for questions to be able to do cross-references, nice-to-have for everything else.

**Comment by MarekSuchanek** [comment]
It needs to be `/{packageId}/question/{uuid}`

**Comment by janslifka** [comment]
URLs move to separate issue https://github.com/DataStewardshipWizard/dsw-common/issues/127
