### ISSUE TITLE
Back up production database

### ISSUE THREAD

**Issue by vknaisl** [DataStewardshipWizard/dsw-common#103]
We are heading to a real production use. It would be nice to regularly back up a production database.

- [x] Implement on production database
- [x] Describe our solution to public docs

**Comment by perglr** [comment]
I  would say, this is an external topic independent of Backend. E.g. @MarekSuchanek maintains a nice script for incremental backup at our CCMi server, which may be used if some Mongo-dumping tool is plugged in.

**Comment by vknaisl** [comment]
Yes, I removed the label. 
Okay, great news!

**Comment by MarekSuchanek** [comment]
I will try some even more basic script without incremental tgz. It is now on server, let's see how it works and then I will improve/document it.

**Comment by vknaisl** [comment]
From my side it’s sufficient for now
