### ISSUE TITLE
Reproducible Docker image building

### ISSUE THREAD

**Issue by touwwouter** [DataStewardshipWizard/dsw-common#104]
As a user who wants to customize local builds beyond plain configuration, I'd like to be able to build custom versions of server and client Docker images. This means having a Dockerfile and docker-compose.yml in the repository in a fork and run

`docker-compose up -d --build`

to get a fully functional image up and running. Probably either the base images with the dependencies for building the server and client have to be available, or the current Dockerfiles will need to be adapted to include all the build steps.

Adapted from #73 which fixes container deployment (not image building).

**Comment by vknaisl** [comment]
Tutorial can be found in public docs (https://docs.dsw.fairdata.solutions)
