### ISSUE TITLE
Password requirements

### ISSUE THREAD

**Issue by touwwouter** [DataStewardshipWizard/dsw-common#105]
Enforce password rules when users sign up and select a password.

**Comment by touwwouter** [comment]
Some standard rules that might be considered:

- [ ] minimal password length 8 characters;
- [ ] passwords must consist of a combination of upper and lower case alphanumeric characters, numeric characters and non-alphanumeric ("special") characters;
- [ ] password history of 12 previous passwords (prohibit old password 'cycling');
- [ ] password expires after 90 days;
- [ ] account lockout threshold after 3 invalid logon attempts. Dependent on the security risk, the account can be locked-out temporarily or should remain locked out until an administrator unlocks it manually.

**Comment by vknaisl** [comment]
Moved to Jira: https://ds-wizard.atlassian.net/browse/DSW-82
