### ISSUE TITLE
I18N

### ISSUE THREAD

**Issue by rwwh** [DataStewardshipWizard/dsw-common#106]
There is an upcoming need to internationalize the wizard. This will require internationalization of both the code and the knowledge model.

**Comment by rwwh** [comment]
I think it would be good to use "gettext" for this. There are many repeated strings in the knowledge model which would be well taken care of using gettext and all the available tools surrounding it.

**Comment by vknaisl** [comment]
Moved to Jira: https://ds-wizard.atlassian.net/browse/DSW-73
