### ISSUE TITLE
Knowledge model editor: List of items doesn't save question

### ISSUE THREAD

**Issue by aderidder** [DataStewardshipWizard/dsw-common#107]
Hi, 
I'm playing around with the Knowledge model editor on https://app.dsw.fairdata.solutions 
Somewhere in my knowledge model I am trying to add a "List of items" with a couple of questions, but I'm having some issues:

1.  I add the new question to the list 
![image](https://user-images.githubusercontent.com/9414840/42684298-f1ef1428-868f-11e8-8d25-33bb52aa2d6e.png)
2. I go back and save my model
3. When I look at the list the question is not there
![image](https://user-images.githubusercontent.com/9414840/42684659-0b5b034e-8691-11e8-8230-014cd4895c33.png)

Another (perhaps related) oddity is that when I specify the question in the list and try to add options to it I cannot add two different options:

1. I add the option
![image](https://user-images.githubusercontent.com/9414840/42684502-8ba75eae-8690-11e8-81f4-9a25597d00ef.png)
2. When add a second option, it modifies the first option, using the label of the second option
![image](https://user-images.githubusercontent.com/9414840/42684545-b0dc2b46-8690-11e8-98f8-127e1d0c520c.png)

Cheers,
Sander

**Comment by janslifka** [comment]
Hello Sander,

thanks for the thorough report. We are aware of this issue. Some major changes to the editor are in progress now (DataStewardshipWizard/dsw-common#58) and it will fix the issue once finished.

Current workaround is to first change the type of the question, save the whole knowledge model (back to the list view) and open it again. Then you should be able to add items or options, based on the type.

**Comment by aderidder** [comment]
Hi, 
Great news that you're making improvements. I opened the topic but did not find a full list of expected changes; is there a list of what these will include? I have a couple of more features I am currently missing, so I'm curious as to whether they will be included. I can also create a new topic for them.

As for the workaround, I'm still ending with an empty List of items. Here's what I tried:

Start:

1. Add Chapter: TestChapter
2. Add Question (Type = String): TestQuestion 
3. Done --> Done --> Save
4. Navigate back to TestQuestion

Version 1:

1. Set Question type to List of items
2. Add item question (Type = String): ItemQuestion1
3. Done --> Done --> Done --> Save   
4. Navigate back to TestQuestion
Result: Iten Question is gone

Version 2 (extra save after setting type to list of items):

1. Set Question type to List of items
2. Done --> Done --> Save
3. Navigate back to TestQuestion
4. Add item question (Type = String): ItemQuestion1
5. Done --> Done --> Done --> Save   
6. Navigate back to TestQuestion
Result: Iten Question is gone

Am I missing a step in the workaround?

**Comment by janslifka** [comment]
Hi,

we've deployed the new editor so the workaround is no longer needed. You can try it out.

I'm closing this issue since it is resolved. If you have more issues or suggestions feel free to open new issues for them.
