### ISSUE TITLE
all the cross-links between items in the data stewardship mind map to the knowledge model

### ISSUE THREAD

**Issue by roper79** [DataStewardshipWizard/dsw-common#11]
- [x] Design decision whether we need just a "reference text" or also an "anchor"
- [x] Associated changes in the schema
- [x] Update the three existing xref links to the new schema
- [ ] Rob puts the cross references into the KM, some of them from A->B as well as B->A.
- [ ] UI implementation

**Comment by MarekSuchanek** [comment]
Some quirks:
- Links are bi-directional, but there will be one direction in the KM
- How to manage the links to unanswered hierarchy of questions?

**Comment by rwwh** [comment]
On the first quirck, plus details.
- It is better to add each bidirectional link twice: from A to B and from B to A.
- I will need a reference text: why are you being referred. E.g. "This question deals with creating reference data. For use of reference data, see: <crossreference>"
- We could use use "anchor" for this like in "weblink", but it may be better to have the explanatory text itself not be the link, but use a standard icon for a crosslink. 
This would need to be decided by the UI designer before we can change the KM schema, and only when the KM schema is adapted, I can add the links.

Can we have it in an hour please? ;-)

**Comment by MarekSuchanek** [comment]
Let's solve this asap, because #62 is being implemented (server is done and client in progress)...

So, we will have just new (optional?) attribute for xref called... "text" or "description"?

**Comment by MarekSuchanek** [comment]
Let's work on this here: https://github.com/DataStewardshipWizard/ds-km/pull/21 

I updated the schema to include mandatory description of xref. You can now work on this in branch `xrefs`. In the mean time, the #62 will be adjusted and prepared...

( You've already started :+1: )

**Comment by rwwh** [comment]
Remark on the second quirck: To solve this, if a question is still closed, the user interface could trace back to a higher level question that has been opened already. We could even make it such that this will be apparent from the way the link is shown: "link to a question that is not yet open" could be shown in a different way as "link to a question that is already open". 

Maybe it is also useful for a user to know whether it is a forward or a backward link?
