### ISSUE TITLE
Question text in KM should be optional

### ISSUE THREAD

**Issue by vknaisl** [DataStewardshipWizard/dsw-common#113]
Currently we require to fill also a question text in Knowledge model but it should not be required.

**Comment by rwwh** [comment]
Can you give an example of a question that should be without a text?

**Comment by MarekSuchanek** [comment]
For example: https://github.com/DataStewardshipWizard/ds-km/blob/master/datamodel/core/chapter1.json#L160

**Comment by rwwh** [comment]
That "text" field has always been optional? Is this issue editor specific?

**Comment by MarekSuchanek** [comment]
In ds-km it has been. This is related just to the Wizard (client+server), server can be tricked by empty string but client does not allow that and requires some text (e.g., space).
