### ISSUE TITLE
PDF export: 504 timeout for large questionnaires

### ISSUE THREAD

**Issue by MarekSuchanek** [DataStewardshipWizard/dsw-common#114]
Exporting PDF causes **504 Gateway Time-out** for core knowledge model (or its customizations). Other (smaller) looks OK, it can be problem with:

- size of HTML that should be converted to PDF 
- some elements in HTML that are hard for wkhtmltopdf to be converted

Further investigation needed...

**Comment by MarekSuchanek** [comment]
Some magic is going on there... For simpler knowledge models, it works well. But when I export HTML (for those where PDF fails) and convert HTML to PDF with FromHTML that is used within dsw-server, it works quickly and correctly.

**Comment by MarekSuchanek** [comment]
Looks like the problem is triggered by Creating pipe for stderr in FromHTML but not using it... which is weird, esp. when it works in some cases.

**Comment by MarekSuchanek** [comment]
Should be solved with https://github.com/DataStewardshipWizard/dsw-server/pull/16

**Comment by janslifka** [comment]
Still not working.

**Comment by MarekSuchanek** [comment]
Testing it with default KM from `Development` mode is not enough - it needs something more complex, like ELIXIR root KM.

**Comment by vknaisl** [comment]
It should work now on staging. Will be deployed to production.

@janslifka please add button with PDF export to production application
