### ISSUE TITLE
Renaming anchor in URL reference

### ISSUE THREAD

**Issue by MarekSuchanek** [DataStewardshipWizard/dsw-common#120]
Think about renaming "anchor" in URL Reference as commented in #62. It should be clear to the end user what they are filling-in.

@janslifka 
> I would suggest calling it something else than **anchor** then because I find it quite confusing. Something like **title** or **label** would be more clear in my opinion.

**Comment by perglr** [comment]
Anchor looks like an ontologically different concept from our situation: in HTML you start with text and you tag it, so you "put an anchor" to a piece of text, while our situation is the opposite: we have a Reference object with a attributes that is rendered (which we do not care here how). So for me label is a proper naming, as it suggests we have a textual representation of the Reference object.
