### ISSUE TITLE
Questions gone missing...

### ISSUE THREAD

**Issue by aderidder** [DataStewardshipWizard/dsw-common#122]
Hi, 
Not a clue on how to reproduce this exactely, but basically what happens is:
* I have a question, List of items type, with 1 question and 4 answers. Each of these answers has ~10 follow-up questions, some of which have additional follow-ups etc (including some with the List of items type). 
* I press the save button every now and then and of course before I log out
* This morning when I checked only the very first question remains but the List of items is empty. So basically all my questions and follow-up questions are gone.... 
* This has happened twice to this specific question with all its subquestions now

I don't know whether something happens over night or whether it got corrupted during the last save, but hopefully you have logs which show what went wrong and how it can be fixed...

**Comment by vknaisl** [comment]
Hi,
I can't see any error in logs (but still it might happened some failure). But there is a change that since all things are seen by everyone and everyone can edit everything, another person could edit your Knowledge Model and remove these questions from Knowledge Model. If it is not reproducible I assume that it could have been like that. 
We purge the knowledge models 1-2 times per month when we release a new version of Wizard which changes the Knowledge Model structures. But there wasn't any release in last 2 week. Next release is planned for this weekend.

**Comment by aderidder** [comment]
Hi,
It would surprise me if someone specifically went through the effort of manually deleting 4 questions twice. However, I do understand that if no error was logged and no clear way of reproducing it, debugging becomes a bit of a nightmare. So let's see what happens in the future.

As for the purging part, is there some way for me to not lose everything? I'm extremely reluctant to re-enter my datamodel if I will lose it again in two weeks time, since it takes me a couple of days to enter everything and it's also too unpredictable; I had planned on giving a demo this morning only to find everything gone. How does this work for e.g. Rob and his data model? I don't think he manually reenters everything, right? 
Maybe we should move this to a new Issue, as it's not really related to the original issue.

**Comment by perglr** [comment]
Dear Sander, we are very sorry for the troubles. The truth is that Wizard is now in intensive development and we cannot guarantee compatibility between major changes of data model --- although migrations of existing data may be technically possible, they are way out of our capacity now. 

Moreover, the demo installation serves primarily as a showcase of the features. If you want to use the Wizard for a serious job, we recommend running your own installation; it is relatively easy thanks to Docker and you find the instructions in https://docs.dsw.fairdata.solutions.

We do not offer an enterprise version, yet, however, if your company is interested in an enterprise-grade support, please contact us, we can discuss that.

This having said, we should definitely do a better job of informing our users of important news; we are now preparing a newsletter system, coming soon ;-).
