### ISSUE TITLE
DMP to DSW redirects

### ISSUE THREAD

**Issue by MarekSuchanek** [DataStewardshipWizard/dsw-common#130]
As we have all functionality previously supported by dmp.fairdata.solutions, we should stop the old wizard. Somewhere are still the old URLs (for example, in the book) which should be operational and lead user to corresponding DSW page. We have two options:

1. Write rules at web server that hosts dmp.fairdata.solutions that will use 302 redirect based on patterns:
  * `dmp.fairdata.solutions/resources/{shortuid} -> app.dsw.fairdata.solutions/book-references/{id}`
  * otherwise to dsw.fairdata.solutions
2. Use CNAME DNS record and reconfigure web server that hosts dsw.fairdata.solutions in same way as above

----

- Is route to book resource only one that needs such treatment or are there any others? (Please edit this text to improve that.)
- How should we do it? Option 1, 2, or some other?

**Comment by rwwh** [comment]
CNAME looks cheaper to me in the long run. What are the disadvantages?

**Comment by MarekSuchanek** [comment]
In both cases, HTTP server configuration is needed (rewrite rules)... and with CNAME, we need Luiz to adjust DNS. 

Now, I changed the config at our CCMi server, so it redirects DMP to DSW (root and book references) correctly. In the future, we might move it to the server where DSW is hosted.

**Comment by MarekSuchanek** [comment]
It is now done and working... everything on DSW server!
