### ISSUE TITLE
Wildcard HTTPS certificates

### ISSUE THREAD

**Issue by MarekSuchanek** [DataStewardshipWizard/dsw-common#133]
We have many subdomains for dsw.fairdata.solutions and we want HTTPS for everything. Wildcard certificate(s) are suitable... 

- https://en.wikipedia.org/wiki/Wildcard_certificate
- https://letsencrypt.org/2017/07/06/wildcard-certificates-coming-jan-2018.html
- https://community.letsencrypt.org/t/wildcard-domain-step-by-step/58250

**Comment by vknaisl** [comment]
I would postpone it now. There will be some changes due to Elixir, GoFair, DSM,.. so I would solve it after all these things will be clear.

**Comment by vknaisl** [comment]
Moved to Jira: 
https://ds-wizard.atlassian.net/browse/DSW-86
