### ISSUE TITLE
Extend the wizard knowledge model with expertise from ELIXIR platforms (through interviews and/or workshops)

### ISSUE THREAD

**Issue by roper79** [DataStewardshipWizard/dsw-common#14]
Required in the project: 
- [ ] Interoperability: Linking out to standards, formats and databases in FAIRsharing: #40 
- [ ] Data: Referrals to the recently published ELIXIR suggestions for deposition databases /Rob/
- [ ] Computing: Suggestions for best practices and (suggestions how to choose suitable) computing infrastructures /Rob + Rachel/

Further ideas:
- [ ] #84

**Comment by vknaisl** [comment]
Make analysis of FAIR Sharing metamodel and APIs
