### ISSUE TITLE
Question types

### ISSUE THREAD

**Issue by vknaisl** [DataStewardshipWizard/dsw-common#18]
We need to have a select box where user can choose type of question.
Currently supported types are:
- Currently there is just one type of question

- Subtasks:
  - [ ] Specify question types
    - Proposed types:
      - Option (radio buttons)
      - List (list of inputs with possibility to add/remove input)
      - String (classic input box)
      - Number (classic input box)
      - Date (classic input box)
      - Text (text area)
  - [ ] Propose UI for Editor and Wizard
  - [ ] Implement

**Comment by MarekSuchanek** [comment]
- How about checkboxes (multi-choice)? If yes, min/max of possible answers?
- Is the minimal required number of answers in *list* always 1?

@rwwh could you please take a look at this issue? Is the list complete for now (and the nearest few weeks/months)?

**Comment by rwwh** [comment]
I am happy with this, it supports the questions that we have at the moment. One thing that sets our system apart from many others is the fact that most questions can be answered by clicks, and only in rare cases people get text fields.

If I'm dreaming very far ahead: I loved the way the "Python megawidgets" dealt with string types! They defined a callback function for every field that can be called with the string contents and responds with "OK" "INCOMPLETE" or "INVALID". The function is called for every key press in the input field. If it responds "INVALID" the key press is refused (e.g. when the user presses "a" in a numeric field, the "a" does not even show up); it makes the background of the field "light red" if the "INCOMPLETE" answer is given (e.g. an e-mail address without @ or tld, or a number outside expected ranges), and it turns the background of the field back to grey for "OK" values. I have implemented this myself once with callback functions written in Tcl. This really helps users to fill in values, and at the same time limits the number of variable types.

Being part of RDA, I also should think about the Data Type Registry... but that may be even more distant future. http://typeregistry.org/registrar/#objects/11314.3/0a9062a9cb51995dea9f

**Comment by perglr** [comment]
"Python megawidgets"-style fields and also autocomplete is definitely planned (AJAX autocomplete already works in the current FormEngine).

Data Type Registry is a great thing, however I miss some measurement ontology behind it, such as http://stattrek.com/statistics/measurement-scales.aspx?Tutorial=AP or http://ceur-ws.org/Vol-1301/ontocomodise2014_9.pdf

**Comment by janslifka** [comment]
Based on the discussion with @vknaisl here is the summary of question types, their transitions and its relationship to events

# Options
- list of answers
	- answer can have follow up question

## Transitions
- => **String, Number, Date, Text**
	- Edit event for changed type is generated
		- answers = Nothing
- => **List**
	- Edit event for changed type is generated
		- answers = Nothing
		- item = Just Item


# String, Number, Date, Text
- no answers

## Transitions
- => **Options**
	- Edit event for changed type is generated
		- answers = Just []
- => **List**
	- Edit event for changed type is generated
		- item = Just Item


# List
- list of items
	- title
	- follow up questions

## Transitions
- => **Options**
	- Edit event for changed type is generated
		- item = Nothing
		- answers = Just []

- => **String, Number, Date, Text**
	- Edit event for changed type is generated
		- item = Nothing

**Comment by vknaisl** [comment]
We introduced a new type which wraps changed values in Edit events - EventField. Serialization to JSON looks like:
```
# Something changed
{
   changed: true,
   value: <value>
}
# Nothing changed
{
   changed: false
}
```

**Comment by perglr** [comment]
@janslifka Put the ontology of question types vs FormEngine into Wiki docs

**Comment by vknaisl** [comment]
Server part is completed

**Comment by janslifka** [comment]
Client part is also completed.
