### ISSUE TITLE
Public registration for Portal

### ISSUE THREAD

**Issue by vknaisl** [DataStewardshipWizard/dsw-common#19]
## Affected system:
- [x] Server
- [x] Client

**Comment by janslifka** [comment]
Also add settings if the public registration is open to configuration.

**Comment by vknaisl** [comment]
# Proposed changes

## Changes in Data Model
### User
- add flag `isActive`(Boolean)
### ActionKey
- `uuid: UUID`
- `userId: UUID`
- `type: enum (REGISTRATION | RESET_PASSWORD)`
- `hash: String`
- `createdAt: DateTime`

## API Changes
### POST /users
- Change to PUBLIC endpoint
- Server will send confirmation email and until that - user can't login to his account because it's inactive.
- Server will create a record in ActionKey table
### GET /activation/{hash}
- PUBLIC endpoint
- Activate user if hash corresponds to a record in table

**Comment by vknaisl** [comment]
Server part done.

@janslifka after finishing client side, please close this issue

**Comment by janslifka** [comment]
Client is ready.

@vknaisl you can close this once the confirmation emails work.

**Comment by vknaisl** [comment]
Mailing done
