### ISSUE TITLE
Unify naming convention

### ISSUE THREAD

**Issue by vknaisl** [DataStewardshipWizard/dsw-common#22]
It will be solved together with @rwwh.

Terms to refactor:
- Knowledge Model
- Package
- Release
- Branch
- Editor
- ...

**Comment by MarekSuchanek** [comment]
One more (related to #35):
- How is the "Wizard" (tool for filling the form and creating the plan) now called? Because now is "Wizard" the whole solution with user management, editor, package registry, ..., and this tool. This tool is very important, so we should think up some good name for it.

**Comment by perglr** [comment]
Let us call it "The Questionnaire"

**Comment by MarekSuchanek** [comment]
# DSW terminology: proposal

- **(DS) Wizard** = our portal solution for Data Stewardship Planning
- **Knowledge Model (KM)** = collection of Data Stewardship knowledge (generic, domain, subdomain, ...), can be based on some parent KM (~localization)
- **Editor** = tool to edit the knowledge model -> create knowledge units = event (add, edit, delete)
- **Migration** = upgrade KM with newer version of parent KM
- **(KM) Package** = published version of KM (list of knowledge units) that can be used in the Questionnaire, it can be exported/imported and further extended
- **Questionnaire** = interactive browsing and completing the questions of selected KM package
- **(DM/DS) Plan** = results of filling-up the Questionnaire for specific package (name & version) - raw data and generated report (template defined in KM)

----

Please comment on this... @vknaisl @janslifka @perglr

**Comment by perglr** [comment]
Good first draft, @MarekSuchanek , please put it to Wiki.

**Comment by vknaisl** [comment]
I like it

**Comment by MarekSuchanek** [comment]
Once we agree on some starting version I will put it to wiki as "Glossary"

I think most confusing are Knowledge Model & Package now... Maybe we should change the name of "Knowledge Model" to something else...

**Comment by MarekSuchanek** [comment]
Initial version done @[DataStewardshipWizard/dsw-common/wiki](https://github.com/DataStewardshipWizard/dsw-common/wiki)
