### ISSUE TITLE
Create guides for users and admins

### ISSUE THREAD

**Issue by vknaisl** [DataStewardshipWizard/dsw-common#23]

**Comment by MarekSuchanek** [comment]
Initial (mosty brief usage) documentation: https://ds-wizard.gitbook.io/dsw/

- It should sync with https://github.com/DataStewardshipWizard/docs
- It is quite simple to use
- If all of us likes it:
  - I will contact Luiz to setup custom DNS: docs.dsw.fairdata.solutions (ok?)
  - I will contact GitBook for free Startup plan: https://www.gitbook.com/pricing#contactus

**Comment by MarekSuchanek** [comment]
Documentation is now working: https://docs.dsw.fairdata.solutions 🎉 

Simple guides for various roles are here: https://docs.dsw.fairdata.solutions/usage and will be continuously improved together with the Wizard.

Message from GitBook -> it is still beta, we will be informed when we can apply for better free plan as open-source project.
