### ISSUE TITLE
User testing scenarios

### ISSUE THREAD

**Issue by vknaisl** [DataStewardshipWizard/dsw-common#25]
Prepare user testing scenarios for features up to end of April (Knowledge Model Editor and Wizard)

**Comment by MarekSuchanek** [comment]
@rwwh here are some scenarios: https://docs.google.com/document/d/1b32WJLQEaWiJmUFRC_TLlHi6DF9-qgmlp6xLQguadWQ/edit?usp=sharing

- Is it too brief?
- What should be covered in more detail?
- If specific questions and answers should be used for working with DSW, could you please provide them or use our document as starter for your more-elaborated version?

**Comment by rwwh** [comment]
I think the exercises are ok, but we should have someone with more didactic background have a look at the learning goals and the steps. Mateusz (@mkuzak) would be my first help line.

**Comment by mkuzak** [comment]
Can someone assign this issue to me? I don't have the permissions to do this.

**Comment by MarekSuchanek** [comment]
_Update_: In Leiden, we discussed these scenarios and concluded that those from provided gdoc above will be used as practical steps in the Wizard that can be mapped to real use cases and scenarios (real or real-like projects).

1. **CZ**: Add scenarios to documentation (https://docs.dsw.fairdata.solutions)
2. **NL**: Find/Create some real usecases/scenarios and map them with the steps
3.  (That will allow to close this issue)
4. **CZ**: #61 based on real scenarios

**Comment by mkuzak** [comment]
I will be working on the scenarios together with Wei Gu, from Luxemburg node, after 23rd of July.
