### ISSUE TITLE
Indications in Wizard

### ISSUE THREAD

**Issue by perglr** [DataStewardshipWizard/dsw-common#3]
Each chapter will indicate number of unanswered questions, FAIRness and desirability. "Easy" extension to other metrics should be possible.

### Server (https://github.com/DataStewardshipWizard/dsw-server)
- [x] Implementation
- [x] Test
- [x] API Docs

### Client (https://github.com/DataStewardshipWizard/dsw-client)
- [x] Done

### Data Management Plan Template
- [x] Done

**Comment by perglr** [comment]
The desirability is bound to the "phase"

**Comment by MarekSuchanek** [comment]
After discussion, there should be following indications in the questionnaires (for each chapter and whole questionnaire):

- number of questions waiting for answering (e.g., X unanswered)
- number of answered questions (e.g., X answered)
- indication if chapter is completed or not (maybe not started yet)
- evaluation of metrics (display FAIRness in nice way, all metrics with some [progress bars](https://getbootstrap.com/docs/4.1/components/progress/#backgrounds)) -> weighted average and number of questions answered related to that metric
- costs (in the future)

**Comment by perglr** [comment]
Separate into issues:

1. Indications will be unanswered questions only: total / desirable (on client)
2. Metrics report on click (server): G,O,F,A,I,R,..
3. Costs report

**Comment by vknaisl** [comment]
# API Proposal

## `GET /questionnaire/report`

```
{
    "uuid": "ea904b03-3e20-45de-ad75-e85f547d9187",
    "chapterReports: [
        {
            "chapterUuid": "a8a6944f-6e73-4e2b-a836-e6fd9657228a",
            "indications": [
                {
                    "type": "AnsweredIndication", 
                    "answered": 10,
                    "unanswered": 5, 
                }
            ],
            "metrics": [
                {
                    "uuid": "99250650-526e-4580-87c3-a81817528883",
                    "measure": 2.4
                },
                {
                    "uuid": "04799df5-e720-42cb-8a70-b009a97909eb",
                    "measure": 1.3
                },
                {
                    "uuid": "5021d353-506a-4e6d-bd13-389626e4dd9c",
                    "measure": 1.9
                }
            ]
        }
    ],
    "createdAt": "2018-06-27T16:24:12Z",
    "updatedAt": "2018-06-27T16:24:12Z"
]
```
