### ISSUE TITLE
Update the leaflet

### ISSUE THREAD

**Issue by perglr** [DataStewardshipWizard/dsw-common#33]
- [x] Use everywhere just name "Data Stewardship Wizard" (DSW)

**Comment by MarekSuchanek** [comment]
OK ... so no more:

- Data Stewardship Portal
- Data Stewardship Planning Portal
- Data Management Planning Portal

**Comment by MarekSuchanek** [comment]
By the way, we should also change the name of GitHub organization... https://github.com/DataStewardshipPortal

**Comment by perglr** [comment]
Data Stewardship Wizard will be the encompassing name and we will discuss naming of its components and device some nice architecture picture ;-)

**Comment by MarekSuchanek** [comment]
Draft of new SVG leaflet to be more open & evolvable: https://github.com/DataStewardshipWizard/dsw-leaflet/pull/1
