### ISSUE TITLE
Texts proof-reading

### ISSUE THREAD

**Issue by perglr** [DataStewardshipWizard/dsw-common#41]

**Comment by vknaisl** [comment]
@perglr I extracted all texts into one file (`lib/Common/Localization.hs`). You can edit all texts here. Some texts are not shown (and will not be shown) to user. But you can edit them anyway. If you have some question about errors meaning, don't hesitate to ask me

**Comment by vknaisl** [comment]
Deployed to staging

**Comment by vknaisl** [comment]
Deployed to production
