### ISSUE TITLE
Prepare for production

### ISSUE THREAD

**Issue by vknaisl** [DataStewardshipWizard/dsw-common#44]
## Technical issues
- [x] Create staging environment 
  - New staging instances
  - New subdomens
- [x] Secure Mongo
  - Add admin, prod and staging user
  - Set up permissions
- [x] Add secure secret for JWT Tokens
- [x] Data and schema migrations for Mongo
- [x] Add profiles (PRODUCTION / STAGING / DEVELOPMENT / TESTING)

## Data
- [x] Prepare production data

**Comment by janslifka** [comment]
We should also set different pipelines in travis for each project
- Deploy docker image with `latest` tag from master branch
- Deploy docker image with version tag from tags
- Don't deploy any image from other branches

Also some kind of continuous delivery would be nice
- Deploy automatically from master to staging
- Deploy automatically from tags to production

**Comment by janslifka** [comment]
I moved the deployment things to another issue https://github.com/DataStewardshipWizard/dsw-common/issues/49
