### ISSUE TITLE
Events refactoring

### ISSUE THREAD

**Issue by janslifka** [DataStewardshipWizard/dsw-common#51]
- Unify events for Questions, FollowUpQuestions, AnswerItemQuestions
- Add path field

### Parts
- [x] [Client](https://github.com/DataStewardshipWizard/dsw-client)
- [x] [Server](https://github.com/DataStewardshipWizard/dsw-server)
- [x] [schema](https://github.com/DataStewardshipWizard/dsw-kmp-validation)
- [x] [km2events](https://github.com/DataStewardshipWizard/km2events)
- [x] [kmp-elixir-root](https://github.com/DataStewardshipWizard/kmp-elixir-root)

### Data Migration
- [x] Convert to path
- [x] Add path to Knowledge Model Event

**Comment by janslifka** [comment]
This is how the path might look like for follow up question

```
{
	"path": [{
		"type": "km",
		"id": "abf003f7-c047-4f3c-804f-df85dfa90949"
	}, {
		"type": "chapter",
		"id": "50aefb59-ebbb-4a65-a187-46c170691803"
	}, {
		"type": "question",
		"id": "a59f94c7-1ae3-438e-86c0-e54bcf06454b"
	}, {
		"type": "answer",
		"id": "c5b6b38a-6783-487e-8bfd-69f2f38b319a"
	}],
	"questionId": "c66f6a97-0949-412e-8e0a-a663d876183d"
	...
}
```

**Comment by MarekSuchanek** [comment]
- Should we `id` or `uuid` (as is now)?

Tradeoff (not so bad probably): we will lose way how to syntactically check that there is correct amount of UUIDs in path hopefully pointing to correct type.

Draft in schema: https://github.com/DataStewardshipWizard/dsw-kmp-validation/pull/5

- I removed followUpQuestion and answerItemTemplate(Question) and added followUpIds to question.

**Comment by vknaisl** [comment]
It should be `uuid`

**Comment by MarekSuchanek** [comment]
So now... Instead of Questions, FollowUpQuestions, AnswerItemQuestions there is only Question event that has path containing:

1. km & chapter -> normal "root" Question
2. km & chapter & question, and non-null "answerItemTemplate" attribute (to define title for items) -> AnswerItemQuestion
3. km & chapter & question & answer -> FollowUpQuestion "on answer - option"

Correct?

**Comment by vknaisl** [comment]
Probably yes

**Comment by MarekSuchanek** [comment]
I've done refactoring in:

- https://github.com/DataStewardshipWizard/km2events/pull/3
- https://github.com/DataStewardshipWizard/dsw-kmp-validation/pull/5

The knowledge model with paths is on Google Drive in Data folder. For me, the load works - please verify if all OK. Then I will merge PRs and update [DataStewardshipWizard/kmp-elixir-root](https://github.com/DataStewardshipWizard/kmp-elixir-root)... Then we will be able to close this issue :grinning:

**Comment by MarekSuchanek** [comment]
Fixed full-path:

-  https://github.com/DataStewardshipWizard/dsw-kmp-validation/pull/5/commits/91b290133a6fa960c20f0185c6295355b722e602
-  https://github.com/DataStewardshipWizard/km2events/pull/3/commits/87e07e0226ea150d39f57c6a53bf6b6cd47d9ddd
-  https://github.com/DataStewardshipWizard/kmp-elixir-root/commit/dbf1eb92482e8ef8977e6c02eecf4ebbb3b3c116
