### ISSUE TITLE
Profile cannot be saved

### ISSUE THREAD

**Issue by perglr** [DataStewardshipWizard/dsw-common#55]
I tried to change the role of Celia to ADMIN

![2018-05-10-093944_1569x610_scrot](https://user-images.githubusercontent.com/4477111/39858212-29dd241a-5436-11e8-9139-e7cb6a55288a.png)

**Comment by janslifka** [comment]
There is some problem with saving the result on the server:

```
{
  "status":400,
  "error":"Bad Request",
  "formErrors":[],
  "message":"Error in $: key \"permissions\" not present",
  "fieldErrors":[]
}
```

**Comment by perglr** [comment]
Still does not work on production

**Comment by vknaisl** [comment]
Yes, it’s deployed just on staging. We will deployed new changes to
production after we set up “stable” branches and taging. Hopefully tomorrow
it should be there :-)


From: Robert Pergl <notifications@github.com> <notifications@github.com>
Reply: DataStewardshipWizard/dsw-common
<reply@reply.github.com>
<reply@reply.github.com>
Date: 15 May 2018 at 13:49:05
To: DataStewardshipWizard/dsw-common <dsw-common@noreply.github.com>
<dsw-common@noreply.github.com>
CC: Vojtech Knaisl <vknaisl@gmail.com> <vknaisl@gmail.com>, State change
<state_change@noreply.github.com> <state_change@noreply.github.com>
Subject:  Re: [DataStewardshipWizard/dsw-common] profile cannot be saved
(#55)

Still does not work on production

**Comment by vknaisl** [comment]
Deployed to production
