### ISSUE TITLE
Gathering community feedback

### ISSUE THREAD

**Issue by perglr** [DataStewardshipWizard/dsw-common#6]
- [x] Clickable small icons for typical feedbacks (showing on hover)
- [x] Textual comment and discussion (Github?) 
- [x] Results/analytics view

## Stories:
- [x] #24

**Comment by vknaisl** [comment]
# Proposal:
We can add two options for every question where user can rate the question. User can either select "thumbs up" (👍 ) or "thumbs down" (👎 ) to rate the question. If user selects "thumbs down"  (👎 ) application will show a modal where user can comment a question.

Suggested types of comments:
- TYPO
- I don't understand the question
- I can't choose any answer
- I propose to add this information to the question
- Other

We should add some indicator to show if a feedback was already processed (mostly for us).

**Comment by perglr** [comment]
A nice-to-have (cheap?) related functionality is marking questions with user flags like "Think more about this section" / "cannot decide". These may be actually used as feedback, as well...
