### ISSUE TITLE
Support other types of references in DSW

### ISSUE THREAD

**Issue by MarekSuchanek** [DataStewardshipWizard/dsw-common#62]
We should support all types of references from ds-km:

- **Resource page** 
  - uuid :: UUID
  - shortUUID :: String ( instead of shortUID as question attribute) - 3 letters shortcut from book
- **URL reference**
  - uuid :: UUID
  - url :: String
  - anchor :: String
- **Cross-reference**
  - uuid :: UUID
  - target :: UUID

### km2events
- [x] Done

### dsw-kmp-schema
- [x] Done

### kmp-elixir-root
- [x] Done

### Client
- [x] Done

### Server 
- [x] Implementation
- [x] Test
- [x] DMP Template

**Comment by MarekSuchanek** [comment]
We need this one in order to actually make use of #69

**Comment by janslifka** [comment]
What exactly is `anchor` at URL reference? If it is an anchor on the page, why can't it be in the URL itself? (e.g. http://example.com/page#anchor)

**Comment by MarekSuchanek** [comment]
It is meant like this: 

```html
<a href="[URL]">[ANCHOR]</a>
```

**Comment by MarekSuchanek** [comment]
Edit bcs of #11 :

**Cross-reference**

- uuid :: UUID
- target :: UUID
- description :: String

**Comment by janslifka** [comment]
OK. I would suggest calling it something else than anchor then because I find it quite confusing. Something like `title` or `label` would be more clear in my opinion.

**Comment by MarekSuchanek** [comment]
Feel free to adjust it within server & client this way. I will change it in km2events and then in ds-km when xrefs are done in order to avoid conflicts.

**Comment by rwwh** [comment]
The "A" in HTML stands for Anchor, and what we put into this field is what is in the "A" of HTML.... hence "anchor" is an appropriate name for this....

**Comment by rwwh** [comment]
OK. Do you propose to name it differently in the user interface only, or to refactor the KM as well?

**Comment by janslifka** [comment]
I think naming it anchor because of the HTML element name is not good even in KM. HTML can be one of many representations of KM. E.g., once we export it to PDF there are no HTML elements but we still have references there.

**Comment by vknaisl** [comment]
I would suggest to have same names in UI and in KM. Otherwise it can lead to some misunderstandings

**Comment by rwwh** [comment]
I am ok with refactoring if there is a good suggestion. Like Robert did when we added the metrics to the KM, I suggest we look for a standard ontology and follow it as much as possible.

Please be aware that once the UI becomes available with i18n the exact label in the UI and in the KM will in any case no longer be the same.

**Comment by rwwh** [comment]
See: http://www.smart-it-consulting.com/article.htm?node=155&page=90#a-anchor-text for the naming from HTML

**Comment by perglr** [comment]
Anchor looks like an ontologically different concept from our situation: in HTML you start with text and you tag it, so you "put an anchor" to a piece of text, while our situation is the opposite: we have a Reference object with a attributes that is rendered (which we do not care here how). So for me `label` is a proper naming, as it suggests we have a textual representation of the Reference object.
