### ISSUE TITLE
Integrate EDAM ontology

### ISSUE THREAD

**Issue by roper79** [DataStewardshipWizard/dsw-common#63]
http://edamontology.org/page

**Comment by MarekSuchanek** [comment]
I did a brief analysis of EDAM Ontology in Protégé... Descriptions of entities/concepts are about OK, sometimes it is not absolutely clear why something is subclass of something else. Some enumerations of disciplines and types of data could be useful.

----

Main question remains - on what level we want to "Integrate EDAM ontology"? 

- Link to terms from KM and show link in the Planner and resulting Plan? 
- Or retrieve the entity via link and display it?
- Use it for enumerations (That is most probably not a good idea, for example formats defined: HTML, JSON, YAML, XML, RDF format, Textual format, Binary format, Format (by type of data). JSON is subclass of YAML and so on. It is kinda mess...)?
