### ISSUE TITLE
Implement GDPR

### ISSUE THREAD

**Issue by vknaisl** [DataStewardshipWizard/dsw-common#68]
We should be conform with GDPR legislation. 

## Web
- [x] Create Privacy page 
- [x] Create link from web footer
- [x] Create contacts page + link from the Privacy page (bottom TODO)

## Client-side changes
- [x] Create checkbox at sign up form

**Comment by perglr** [comment]
Privacy page in https://github.com/DataStewardshipWizard/dsw-web/commit/69cb3384c89ed7f008009137cc17192aca9089a9

**Comment by perglr** [comment]
I finished the contact page, it is now necessary to link it from the Privacy page (TODO placeholder). I am not sure about the link, @janslifka, can you please finalize and close the issue?
