### ISSUE TITLE
KM editor table usability

### ISSUE THREAD

**Issue by MarekSuchanek** [DataStewardshipWizard/dsw-common#71]
While writing guide I encountered few things in the usability of table with KM editors:

1. It should be sorted by names (in the future we might need also filter/pagination for such tables)
2. The "outdated" flag should be different than name of KM editor, color or something like bootstrap badge. It is also not consistent with the "pencil icon" used when you can publish - it is not really clear then. 
3. For icons (that applies in general) there could be tooltips on hover. For editor it might not be clear if you will edit the editor (its name for example, as is in the user management) or open the editor.
4. Migration tool have weird layout... it looks like heading float is broken somehow.

<img width="719" alt="vystrizek" src="https://user-images.githubusercontent.com/9638527/41274448-b75c112e-6e1d-11e8-8e9c-cdfd33e107eb.PNG">

**Comment by janslifka** [comment]
I split this into separate issues:

- DataStewardshipWizard/dsw-common#98
- DataStewardshipWizard/dsw-common#99
- DataStewardshipWizard/dsw-common#100
- DataStewardshipWizard/dsw-common#101
