### ISSUE TITLE
Provide instructions for setting up a reproducible production environment

### ISSUE THREAD

**Issue by touwwouter** [DataStewardshipWizard/dsw-common#73]
As a user, I'd like to clone the repository, perhaps configure some settings, and then run something like

`docker-compose up -d --build`

to get a fully functional (production) image up and running. `docker-compose.yml` and Dockerfile files could be part of the repository.

In more detail:
The current version of Dockerfile assumes the availability of the dsw-server binary rather than setting up the build environment and instructions. The [deployment](https://github.com/DataStewardshipWizard/dsw-server/blob/develop/docs/Deployment.md) guide suggests that fpco/stack-build can be used as a base image as long as the private build servers in the cesnet.cz domain remain inaccessible for public use.
The extra benefit is more explicit installation instructions (see #74).

**Comment by MarekSuchanek** [comment]
Indeed we are ready for this and we will publish it on Docker Hub soon. I made a issue https://github.com/DataStewardshipWizard/dsw-common/issues/77 for that and put it in our Technical Roadmap with high priority...

**Comment by MarekSuchanek** [comment]
Will be done after https://github.com/DataStewardshipWizard/dsw-common/issues/77

**Comment by MarekSuchanek** [comment]
https://docs.dsw.fairdata.solutions/installation#docker

**Comment by touwwouter** [comment]
@MarekSuchanek @vknaisl thanks, this clarifies a lot.

This focuses on container deployment. I created #104 for building Docker images locally.

One other small note, the [instructions](https://docs.dsw.fairdata.solutions/installation#docker-compose) assume the availability of `datastewardshipwizard/crontab`. Of course, this image can be built from DataStewardshipWizard/docker-crontab, but I don't see it in Docker Hub.

**Comment by vknaisl** [comment]
@touwwouter 
`datastewardshipwizard/crontab` - you find the docker image [here](https://hub.docker.com/r/datastewardshipwizard/crontab/). It's a temporary solution. We had to fork original [willfarrell/crontab](https://hub.docker.com/r/willfarrell/crontab/) because currently there is a bug.
