### ISSUE TITLE
Improve installation instructions for server app

### ISSUE THREAD

**Issue by touwwouter** [DataStewardshipWizard/dsw-common#74]
As a user, I'd like to see explicit strategy and example commands for the recommended installation of Haskell, Cabal, Stack, and hpack in the [contributing](https://github.com/DataStewardshipWizard/dsw-server/blob/develop/docs/Contribute.md) or deployment instructions and `Dockerfile`.

**Comment by MarekSuchanek** [comment]
We will gather all textual documentation here: https://docs.dsw.fairdata.solutions

Having just stack and npm (and wkhtmltopdf) installed as they describe in their docs should be sufficient. Do you think https://docs.dsw.fairdata.solutions/installation is ok?

**Comment by touwwouter** [comment]
@MarekSuchanek looks good
