### ISSUE TITLE
Custom styling of client app

### ISSUE THREAD

**Issue by touwwouter** [DataStewardshipWizard/dsw-common#75]
As a user, I'd like to give dsw-client a custom look and feel (e.g. font. logo, colors, and textual changes).

Are there any options to do this and is documentation available?

**Comment by vknaisl** [comment]
Currently it does not exist any way how to do it. But it is possible to implement it. At least some custom logo and custom colors for CSS.

**Comment by touwwouter** [comment]
@MarekSuchanek mentioned perhaps a combination of custom CSS and html templates with mustache (or similar) tags rendered by the Haskell code? This would give a lot of flexibility and is similar to other webframeworks (e.g. Python Flask with Jinja2 templates or Django etc.)

**Comment by vknaisl** [comment]
@touwwouter Just for sure, do you mean to customise Data Management Plan styles or to customise Client Application?

**Comment by touwwouter** [comment]
@vknaisl Both actually, but this issue is for the webapp interface.
I suggested report styling in #5 but have created #93 for report styling.

**Comment by vknaisl** [comment]
Moved to Jira: 
https://ds-wizard.atlassian.net/browse/DSW-94
