### ISSUE TITLE
Collaboration on DMP questionnaires

### ISSUE THREAD

**Issue by touwwouter** [DataStewardshipWizard/dsw-common#76]
As a researcher, I'd like to provide input on collaborator's DMPs.

DMPs created at the project level in practice require input from multiple researchers. It would be nice if users can work together with other users on a specific DMP, for example by inviting them (arrange permissions on the DMP level).

**Comment by vknaisl** [comment]
It's a huge thing to implement permission model for collaboration. But it's totally needed. This current version focuses mainly on demonstrating power of this app and how this app can simplify troubles with Data Management Plans. But for future usage this functionality needs to be implemented

**Comment by vknaisl** [comment]
Moved to Jira: 
https://ds-wizard.atlassian.net/browse/DSW-96
