### ISSUE TITLE
Add phases functionality

### ISSUE THREAD

**Issue by perglr** [DataStewardshipWizard/dsw-common#83]
As a researcher, I would like to see in which phase of the project currently I am, to keep track of questions necessary to answer in a certain moment. I would like to switch the phase in the questionnaire.

There are 3 phases: 
1 - "before submitting the proposal"
2 - "before submitting the DMP"
3 - "before finishing the project"

- Each question has an information, in which phase it is desirable (1-3 or "never"). 
- The default phase of a question is either 2 or if the question has a prerequisite, it is same as it.

**Comment by MarekSuchanek** [comment]
In the [DataStewardshipWizard/ds-km](https://github.com/DataStewardshipWizard/ds-km) "never" is represented as 4. But with Haskell/Elm you can do something more interesting like `Phase x | Never` and km2events will consider it...

**Comment by MarekSuchanek** [comment]
## Affected projects

### km2events
- [ ] Done

### dsw-kmp-schema
- [ ] Done

### kmp-elixir-root
- [ ] Done

### Client
- [ ] Done

### Server 
- [ ] Implementation
- [ ] Test
- [ ] API Docs
- [ ] DMP Template
