### ISSUE TITLE
Error exporting docx and odt

### ISSUE THREAD

**Issue by touwwouter** [DataStewardshipWizard/dsw-common#90]
Errors are raised when exporting docx and odt:

``` json
{
status: 500,
error: "Internal Server Error",
type: "GeneralServerError",
message: "Couldn't transform to desired document format"
}
```

**Comment by MarekSuchanek** [comment]
@touwwouter Please, what is your client/server setup? Both local latest versions from develop or master branch?

**Comment by touwwouter** [comment]
@MarekSuchanek 
dsw-server: local, develop (@ 0b4076b059b7f611d748d4c15e1884baa0a130af)
dsw-client: local, develop latest (5aa69b80378a3eea704ce35f74a4f269fafbf6be)

Ubuntu 16.04
wkhtmltopdf 0.12.2.4-1

**Comment by MarekSuchanek** [comment]
OK, I was able to locate why this is failing. Stack is unable to install our separate package with Pandoc special flags and use it, the flags must be defined in dsw-server stack.yaml as well. This is kinda sad...

```yaml
flags:
  pandoc:
    embed_data_files: true
```

Another problem is that ODT cannot be opened by libreoffice with

![screenshot_2018-07-05_13-09-31](https://user-images.githubusercontent.com/9638527/42320167-afb728d4-8054-11e8-8261-e97d25650238.png)


I will solve those in dsw-server and link the PR here later on...

**Comment by MarekSuchanek** [comment]
The PR https://github.com/DataStewardshipWizard/dsw-server/pull/10 solves the 500 error, but there is problem with ODT (and also something weird with RTF). Those will be solved separately in FromHTML package:

- https://github.com/MarekSuchanek/FromHTML/issues/2
- https://github.com/MarekSuchanek/FromHTML/issues/3
