### ISSUE TITLE
Connect the FAIRness Evaluator

### ISSUE THREAD

**Issue by roper79** [DataStewardshipWizard/dsw-common#92]
https://docs.google.com/presentation/d/1dic-cjskgsecXy_P-r4RINc-jxzmqC4SSFIeBlQ_bdw/edit#slide=id.p

Message channel:
https://ds-wizard.slack.com/messages/CBL0AKRKR/

- [ ] Make a technical analysis & plan
- [ ] Server
- [ ] Client

**Comment by MarekSuchanek** [comment]
Yesterday we had a CZ-team call where we discussed this... 

## Requirements and considerations

- We want to build this (now or in the future) as generic as possible to incorporate various forms of _question -> answer -> feedback (from independent internal/external service)_ workflow: FAIRness evaluator (e.g. testing entered URIs and the content received), found courses/experts/materials related to answer, checking if entered answer is in some list (e.g. FAIRsharing.org), etc.
- We need common interface to call spells on the side of DSW, having everything implemented inside dsw-server is not an option!
- For some evaluations, multiple answers can be required. And, of course, there can be multiple different evaluations (from the same or different evaluator) for the same question. Then it is question when the evaluation should be triggered (i.e., if all of required questions are completed and one of them changes?).
- Some evaluations could be done during filling the questionnaire and some during computation of the summary report. But probably we don't want to separate those concepts (two different types of evaluator adapters), just decide in Wizard when it will be called (up-to settings made by Data Steward).
- There can be different forms of feedback for answer - comment, list of something (e.g. courses), score, etc.
- After implementing it correctly, it would be possible to refactor attributes such as references, experts, metrics, and advices as such evaluators. But what should be easily editable by Data Steward should stay in the KM directly.

## DS Wizard naming

- **Spell** = service acting as adapter to "evaluator", it's specification
- **Ingredients** = requirements of the _spell_ (i.e., what is needed to perform the spell)
- **Incantation** = calling the _spell_ with _ingredients_
- **Enchantment** = result of _incantation_

## Problems, pitfalls, and questions?

- External service acting as evaluator can be out of order (service outage, becomes paid, shut down). Do we need to keep older information stored from this evaluator? Even if it is just in half-done questionnaire?
- Evaluator will be changed - giving different results for the same answers. Should (when/how) the questionnaire reevaluate the answers? Should be a version of evaluator included to make it clear?

## Next

I will create some model and diagram how it could work... Let's design this flexible. On the side of dsw-server, it should be as easy as possible (just sending answers and getting response). For dsw-client it will be probably more complicated - how to represent different types of feedback.

_Note_: Feel free to edit/extend this comment... (GitHub supports to show changes)

**Comment by MarekSuchanek** [comment]
@perglr @rwwh Is there some repository public with the FAIRness evaluator sources? We should have some link in this issue... 

Best would be if we contribute directly to such repo and dockerize the server app so we can easily deploy it...

**Comment by perglr** [comment]
Mark Wilkinson is the owner of this, he should be reachable on the Slack in our group.

**Comment by vknaisl** [comment]
Moved to Jira: https://ds-wizard.atlassian.net/browse/DSW-84
