### ISSUE TITLE
Separate host settings

### ISSUE THREAD

**Issue by janslifka** [DataStewardshipWizard/dsw-common#96]
Moved from DataStewardshipWizard/dsw-client#24.

> In order to approach the wizard remotely, I had to change `package.json`:
> 
> ```
>  "start": "webpack-dev-server --host 0.0.0.0 --public <host>:<port>"
> ```
> 
> and  `src/elm/Requests.elm`:
> 
> ```
> apiRoot = "http://<host>:<port>"
> ```
> 
> It would be nice if these could be made settings, in a config file for example.

**Comment by janslifka** [comment]
We only use docker deployment outside of development environment where the correct host is set up based on ENV variable. So this is not a problem for know.

It might be an issue once we want to serve client without docker image, e.g. from s3 storage.

**Comment by vknaisl** [comment]
Moved to Jira: https://ds-wizard.atlassian.net/browse/DSW-97
