### ISSUE TITLE
Create a useful app's main page

### ISSUE THREAD

**Issue by janslifka** [DataStewardshipWizard/dsw-common#97]
Provide something useful at app's main page, e.g. list of available questionnaires.

**Comment by perglr** [comment]
- As a system admin, I would like to edit the welcome text to customize it for the organization.
- For our pilot instance, write a warning "Warning: DSW is currently in intensive development. Stored DS plans may become incompatible in future versions."

**Comment by janslifka** [comment]
Warning was moved into separate issue https://github.com/DataStewardshipWizard/dsw-common/issues/111

More welcome page settings can be done later.

**Comment by vknaisl** [comment]
Moved to Jira: https://ds-wizard.atlassian.net/browse/DSW-91
